### ISSUE TITLE
Issues with useShopOrigin Hook + possible typo in verify-token API Route

### ISSUE THREAD

**Issue by avcohen** [ctrlaltdylan/shopify-nextjs-toolbox#1]
Hello.

Thanks for all your work on this library. Really clean and helpful.

I seem to always be getting `false` from the useShopOrigin hook and trying to use `getShopOrigin` throws an error: `ReferenceError: window is not defined`.

I've reviewed the [sample repo](https://github.com/ctrlaltdylan/shopify-session-tokens-nextjs) quite a bit and don't feel I'm missing anything — any chance you might have some insight as to what might cause this to not get set?

In the [verify-token route](https://github.com/ctrlaltdylan/shopify-session-tokens-nextjs/blob/master/pages/api/verify-token.js) it notes setting `session_token` on the response object but this is undefined. Digging into the library itself, the `withSessionToken` middleware seems to be setting this to `sessionToken`.

Thanks

**Comment by ctrlaltdylan** [comment]
Hi @avcohen 

`ReferenceError: window is not defined` means that the `getShopOrigin` is being run on the server side when `window` doesn't actually exist because there's no browser.

Double check that you're not calling that function within `getServerSideProps` so that it's running on the browser side only. That should fix your issue.
